### ISSUE TITLE
Upgrade to null safety?

### ISSUE THREAD

**Issue by kmcgill88** [amondnet/flutter_coverage_badge#2]
Any plans to upgrade this to support nulls safety? Are you open to a PR to do the upgrade?

This is a handy tool but I'm getting tired of my project yelling that this isn't upgrade 😄

**Comment by kmcgill88** [comment]
I see you made commits for null safety but it doesn't look like you've published that on pub.dev. Any plans to do so? 🙏🏻

**Comment by amondnet** [comment]
@kmcgill88 
Could you try the method below? If there are no problems, I will publish this weekend.
```
dev_dependencies:
  flutter_coverage_badge:
    git:
      url: https://github.com/amondnet/flutter_coverage_badge.git
      ref: master
```
